language: JAVA
script: mvn install
jdk:
  - oraclejdk8
cache:
    directories:
    - .autoconf
    - $HOME/.m2
before_install:
    -  "mkdir idea"
    -  "./download-unpack-intellij.sh 2017.2.6 idea idea-IC-172.4574.11 $HOME/.m2"
    -  "./install-intellij-libs.sh 2017.2.6 idea $HOME/.m2"
after_failure:
      - cat ./camel-idea-plugin/camel-idea-plugin/target/failsafe-reports/*.txt
      - cat ./camel-idea-plugin/camel-idea-plugin/target/surefire-reports/*.txt
